routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('login');
});
Route::get('login','LoginController@getLogin')->name('login');
Route::post('login','LoginController@postLogin');
Route::resource('clubs', 'ClubsController');
Route::get('logout','LogoutController@getLogout');
Route::resource('players', 'PlayersController');

resources/views/clubs.blade.php
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Premiere League</title>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" />
  <script src="https://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>
  <script src="https://cdn.datatables.net/1.10.12/js/dataTables.bootstrap.min.js"></script>  
  <link rel="stylesheet" href="https://cdn.datatables.net/1.10.12/css/dataTables.bootstrap.min.css" />
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
  <meta name="csrf-token" content="{{ csrf_token() }}">
</head>
<body>
  <nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
      <div class="collapse navbar-collapse navbar-ex1-collapse">
        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <a href="{{url('login')}}" class="dropdown-toggle" data-toggle="dropdown">{{Auth::user()->name}} <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><a href="{{url('logout')}}">Logout</a></li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">    
    <br />
    <h3 align="center">CLUB</h3>
    <br />
    <div align="right">
      <button type="button" name="create_record" id="create_record" class="btn btn-success btn-sm">Add Club</button>
    </div>
    <br />
    <div class="table-responsive">
      <table class="table table-bordered table-striped" id="user_table">
       <thead>
        <tr>
          <th width="10%">Logo</th>
          <th width="30%">Club</th>
          <th width="15%">HLV</th>
          <th width="15%">SVD</th>
          <th width="30%">Action</th>
        </tr>
      </thead>
      <tr>
       
      </tr>
    </table>
  </div>
  <br />
  <br />
</div>
@include('modal.clubsmodal')
@include('modal.deletemodal')
</body>
<script src="{{url('js/clubs.js')}}"></script>
</html>

resources/views/login.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Login</title>
  <!-- Latest compiled and minified CSS & JS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <script src="//code.jquery.com/jquery.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
</head>
<body>
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <form action="{{url('login')}}" method="POST" role="form">
          <legend>Login</legend>
          @if($errors->has('errorlogin'))
            <div class="alert alert-danger">
              <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
              {{$errors->first('errorlogin')}}
            </div>
          @endif
          <div class="form-group">
            <label for="">Email</label>
            <input type="text" class="form-control" id="email" placeholder="Email" name="email" value="{{old('email')}}">
            @if($errors->has('email'))
              <p style="color:red">{{$errors->first('email')}}</p>
            @endif
          </div>
          <div class="form-group">
            <label for="">Password</label>
            <input type="password" class="form-control" id="password" placeholder="Password" name="password">
            @if($errors->has('password'))
              <p style="color:red">{{$errors->first('password')}}</p>
            @endif
          </div>
        
          
          {!! csrf_field() !!}
          <button type="submit" class="btn btn-primary">Đăng nhập</button>
        </form>
      </div>
    </div>
  </div>
</body>
</html>

resources/views/players.blade.php
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Player</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" />
    <script src="https://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.12/js/dataTables.bootstrap.min.js"></script>  
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.12/css/dataTables.bootstrap.min.css" />
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <meta name="csrf-token" content="{{ csrf_token() }}">
</head>
<body>
    <div class="container">    
        <br />
        <h3 align="center">Player</h3>
        <br />
        <br />
        <div align="right">
            <button type="button" name="create_record" id="create_record" class="btn btn-success btn-sm">Add Player</button>
            <input type="text" class="hidden url" value="{{ route('players.store') }}">

        </div>
        <div class="table-responsive">
            <table class="table table-bordered table-striped" id="user_table">
                <thead>
                    <tr text-align="center">
                        <th>Ten</th>
                        <th>Tuoi</th>
                        <th>Vi tri</th>
                    </tr>
                </thead>
                <tbody>
                    @if($products->isNotEmpty())
                    @foreach($products as $players)
                    <tr>
                        <td>{{ $players->name }}</td>
                        <td>{{ $players->age }}</td>
                        <td>{{ $players->position }}</td>
                        <td class="hidden">{{ $players->club_id }}</td>
                    </tr>
                    @endforeach
                    @else
                    <tr>
                        <td colspan="3">not found</td>
                    </tr>
                    @endif
                </tbody>
            </table>
        </div>
        <br />
        <br />
    </div>
    <div id="formModal" class="modal fade" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Add Player</h4>
                </div>
                <div class="modal-body">
                    <span id="form_result"></span>
                    <form method="post" id="sample_form" class="form-horizontal" enctype="multipart/form-data">
                        @csrf
                        <div class="form-group hidden">
                            <div class="col-md-8">
                                <input type="text" name="club_id" id="club_id" class="form-control" value="{{ $players->club_id }}" />
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-4" >Ten : </label>
                            <div class="col-md-8">
                             <input type="text" name="name" id="name" class="form-control" />
                         </div>
                     </div>
                     <div class="form-group">
                        <label class="control-label col-md-4">Tuoi : </label>
                        <div class="col-md-8">
                            <input type="text" name="age" id="age" class="form-control" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-4">Vi tri : </label>
                        <div class="col-md-8">
                            <input type="text" name="position" id="position" class="form-control" />
                        </div>
                    </div>
                    <br />
                    <div class="form-group" align="center">
                        <input type="hidden" name="action" id="action" />
                        <input type="hidden" name="hidden_id" id="hidden_id" />
                        <input type="submit" name="action_button" id="action_button" class="btn btn-warning" value="Add" />
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
</body>
<script src="{{url('js/players.js')}}"></script>
</html>